`timescale 1ns / 1ps

//=============================================================================
// Testbench for HLS-Generated 2D Convolution (PandA Bambu)
//
// This testbench:
//   1. Instantiates the top-level `main` module.
//   2. Drives clock, reset, and start_port.
//   3. Waits for done_port assertion.
//   4. Reads return_port and reports PASS/FAIL.
//   5. Measures execution latency in clock cycles.
//=============================================================================

module tb_main;

    // Clock period in ns
    parameter CLK_PERIOD = 10;

    // Signals
    reg         clk;
    reg         rst;
    reg         start;
    wire        done;
    wire [31:0] return_val;

    // Cycle counter for latency measurement
    integer cycle_count;
    integer start_cycle;
    integer end_cycle;

    // DUT Instantiation
    main dut (
        .clock(clk),
        .reset(rst),
        .start_port(start),
        .done_port(done),
        .return_port(return_val)
    );

    // Clock generation
    initial begin
        clk = 0;
        forever #(CLK_PERIOD/2) clk = ~clk;
    end

    // Cycle counter
    always @(posedge clk) begin
        cycle_count <= cycle_count + 1;
    end

    // Main test sequence
    initial begin
        // Initialize
        rst   = 1'b0;   // PandA Bambu uses active-LOW reset
        start = 1'b0;
        cycle_count = 0;
        start_cycle = 0;
        end_cycle   = 0;

        $display("=============================================================");
        $display("  2D Convolution HLS Design - Functional Verification");
        $display("  Generated by PandA Bambu HLS");
        $display("=============================================================");
        $display("");

        // Hold reset for 10 cycles (active low)
        $display("[%0t] Asserting reset (active low)...", $time);
        repeat(10) @(posedge clk);

        // Release reset
        rst = 1'b1;
        $display("[%0t] Reset released.", $time);
        repeat(5) @(posedge clk);

        // Pulse start_port for 1 cycle
        $display("[%0t] Pulsing start_port...", $time);
        @(posedge clk);
        start = 1'b1;
        start_cycle = cycle_count;
        @(posedge clk);
        start = 1'b0;

        $display("[%0t] Waiting for done_port...", $time);

        // Wait for done_port with timeout
        fork
            begin : wait_done
                @(posedge done);
                end_cycle = cycle_count;
                $display("[%0t] done_port asserted!", $time);
                $display("  Return value: 0x%08h (%0d decimal)", return_val, $signed(return_val));
                $display("  Execution latency: %0d clock cycles", end_cycle - start_cycle);
                $display("");
                // Golden reference check: C main() returns 0
                if (return_val == 32'd0) begin
                    $display("=============================================================");
                    $display("  SIMULATION RESULT: PASS");
                    $display("  Return code matches golden reference (expected: 0, got: 0)");
                    $display("  The 2D convolution completed successfully!");
                    $display("=============================================================");
                end else begin
                    $display("=============================================================");
                    $display("  SIMULATION RESULT: MISMATCH");
                    $display("  Expected return_port = 0, Got = %0d", $signed(return_val));
                    $display("=============================================================");
                end
            end
            begin : timeout
                // Timeout after 100,000,000 cycles (1024x1024 convolution with double FP is huge)
                repeat(100000000) @(posedge clk);
                $display("");
                $display("=============================================================");
                $display("  SIMULATION RESULT: TIMEOUT");
                $display("  Design did not complete within 100,000,000 cycles.");
                $display("=============================================================");
            end
        join_any
        disable fork;

        // Let simulation settle
        repeat(10) @(posedge clk);
        $finish;
    end

    // Monitor state machine transitions (optional debug)
    // Uncomment for deep debugging:
    // always @(posedge clk) begin
    //     if (done) $display("[%0t] DONE! return=%0d", $time, $signed(return_val));
    // end

    // VCD dump for waveform viewing
    initial begin
        $dumpfile("tb_main.vcd");
        $dumpvars(0, tb_main);
    end

endmodule
